version: "3.5"

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432

  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: ./src/backend/docker/Dockerfile.fastapi
    depends_on:
      - database
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=database
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 8000
  
  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: ./src/frontend/docker/Dockerfile.nodejs
    depends_on:
      - nginx
    restart: always
    expose:
      - 8080

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - fastapi
    ports:
      - "80:80"
    volumes:
      - ./src/backend/config/.nginx/default.conf:/etc/nginx/nginx.conf:ro