from python:3.12.4-slim

LABEL name="fastapi"

WORKDIR .
RUN mkdir /src

COPY ./src/backend/config/req.txt /src/req.txt
RUN python -m pip install -r ./src/req.txt

COPY ./src/backend /src/
CMD ["uvicorn", "src.app:app", "--host=0.0.0.0", "--port=8000"]